In [641]:
import numpy as np
import pandas as pd
import re

In [642]:
# pd.set_option("display.max_rows", None)
# pd.set_option("display.max_columns", None)

In [643]:
df = pd.read_csv("../zameenData/zameenData.csv", index_col=0)
df.head()

,agent,name,land_type,price,location,baths,area,pupose,bed,added_days
0,M A Associates,Muhammad Arshad,House,PKR25 Crore,"Garden Town, Lahore, Punjab",6,2 Kanal,For Sale,7,2 weeks ago
1,M A Associates,Muhammad Arshad,Commercial Plot,PKR60 Crore,"Gulberg, Lahore, Punjab",-,2 Kanal,For Sale,-,2 weeks ago
2,M A Associates,Muhammad Arshad,House,PKR15 Crore,"Gulberg, Lahore, Punjab",6,1 Kanal,For Sale,5,2 weeks ago
3,M A Associates,Muhammad Arshad,Commercial Plot,PKR25.5 Crore,"Wahdat Road, Lahore, Punjab",-,5.4 Kanal,For Sale,-,3 days ago
4,M A Associates,Muhammad Arshad,Residential Plot,PKR7.25 Crore,"Garden Town, Lahore, Punjab",-,1 Kanal,For Sale,-,2 weeks ago

In [644]:
df.rename(columns={'pupose':'purpose'}, inplace=True)

In [645]:
def check_columns(df):
    for i in df.columns:
        if i == "pupose":
            return "not changed"

    return "changed"
        
check_columns(df)

'changed'

In [646]:
df = df.drop_duplicates()

In [647]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [agent, name, land_type, price, location, baths, area, purpose, bed, added_days]
Index: []

In [648]:
# for i in df.columns:
#     print("Column:", i)
#     print(df[i].value_counts())
#     print()

In [649]:
df['land_type'].value_counts()

land_type
House                7875
Residential Plot     4771
Upper Portion        1727
Flat                 1320
Lower Portion         760
Office                741
Commercial Plot       525
Building              352
Shop                  206
Plot File             201
Farm House            125
Factory               104
Warehouse              95
Room                   77
Agricultural Land      57
Industrial Land        45
Other                  21
Penthouse              10
Plot Form               3
Name: count, dtype: int64

In [650]:
df.head()

,agent,name,land_type,price,location,baths,area,purpose,bed,added_days
0,M A Associates,Muhammad Arshad,House,PKR25 Crore,"Garden Town, Lahore, Punjab",6,2 Kanal,For Sale,7,2 weeks ago
1,M A Associates,Muhammad Arshad,Commercial Plot,PKR60 Crore,"Gulberg, Lahore, Punjab",-,2 Kanal,For Sale,-,2 weeks ago
2,M A Associates,Muhammad Arshad,House,PKR15 Crore,"Gulberg, Lahore, Punjab",6,1 Kanal,For Sale,5,2 weeks ago
3,M A Associates,Muhammad Arshad,Commercial Plot,PKR25.5 Crore,"Wahdat Road, Lahore, Punjab",-,5.4 Kanal,For Sale,-,3 days ago
4,M A Associates,Muhammad Arshad,Residential Plot,PKR7.25 Crore,"Garden Town, Lahore, Punjab",-,1 Kanal,For Sale,-,2 weeks ago

In [651]:
df.drop(columns=['agent',"name"],inplace=True)

In [652]:
df['purpose'].value_counts()

purpose
For Sale                                                      11013
For Rent                                                       7809
Park View City, Lahore, Punjab                                   35
GT Road, Lahore, Punjab                                          20
Raiwind Road, Lahore, Punjab                                     17
Bahria Orchard, Lahore, Punjab                                   16
Bahria Town, Lahore, Punjab                                      13
New Lahore City, Lahore, Punjab                                   8
Ring Road, Chiniot, Punjab                                        7
Lahore - Jaranwala Road, Lahore, Punjab                           7
Al Rehman Garden, Lahore, Punjab                                  6
Jia Baga Road, Lahore, Punjab                                     5
Gulberg, Lahore, Punjab                                           5
Pine Avenue, Lahore, Punjab                                       5
Central Park Housing Scheme, Lahore, Punjab                       5
Wagha Town, Lahore, Punjab                                        4
Defence Road, Lahore, Punjab                                      4
Paragon City, Lahore, Punjab                                      4
Bedian Road, Lahore, Punjab                                       3
GT Road, Kamoki, Punjab                                           2
Park Avenue Housing Scheme, Lahore, Punjab                        2
Sue-e-Asal Road, Lahore, Punjab                                   2
Shah Jamal, Lahore, Punjab                                        2
DHA Defence, Lahore, Punjab                                       2
Bankers Avenue Cooperative Housing Society, Lahore, Punjab        2
Shahdara, Lahore, Punjab                                          2
Jubilee Town, Lahore, Punjab                                      1
Sukh Chayn Gardens, Lahore, Punjab                                1
Punjab University Employees Society, Lahore, Punjab               1
Ferozepur Road, Lahore, Punjab                                    1
Main Canal Bank Road, Lahore, Punjab                              1
Lahore Motorway City, Lahore, Punjab                              1
Al-Qayyum Garden, Lahore, Punjab                                  1
Johar Town, Lahore, Punjab                                        1
Multan Road, Lahore, Punjab                                       1
Kahna, Lahore, Punjab                                             1
Samanabad, Lahore, Punjab                                         1
Bahria Nasheman, Lahore, Punjab                                   1
Punjab Small Industries Colony, Lahore, Punjab                    1
Alfalah Town, Lahore, Punjab                                      1
Garden Town, Lahore, Punjab                                       1
Name: count, dtype: int64

In [653]:
df.shape

(19016, 8)

In [654]:
df = df[df['purpose'].isin(['For Sale'])]
df.purpose.value_counts()

purpose
For Sale    11013
Name: count, dtype: int64

In [655]:
df.shape

(11013, 8)

# For Price Column

In [656]:
df.price.value_counts()[:10]

price
PKR3.5 Crore     161
PKR75 Lakh       145
PKR2 Crore       132
PKR2.25 Crore    130
PKR1.5 Crore     125
PKR1.1 Crore     123
PKR2.5 Crore     120
PKR65 Lakh       118
PKR1.3 Crore     118
PKR3.25 Crore    110
Name: count, dtype: int64

In [657]:
df.price.head()

0      PKR25 Crore
1      PKR60 Crore
2      PKR15 Crore
3    PKR25.5 Crore
4    PKR7.25 Crore
Name: price, dtype: object

In [658]:
df.price.dtype

dtype('O')

In [659]:
import re

def convert_into_crore(text):

    if text is None or not isinstance(text, str):
        return None

    match = re.search(r"PKR\s*(\d+(?:\.\d+)?)\s*([a-zA-Z]+)", text)

    if not match:
        return None

    value = float(match.group(1))
    unit = match.group(2).lower()

    if unit == "crore":
        return round(value * 100, 2)

    elif unit == "lakh":
        return value

    elif unit == "arab":
        return round(value * 10000, 2)

    return None

In [660]:
# df['price'] = df['price'].apply(convert_into_crore)
df.insert(2,"price_lakh",df.price.apply(convert_into_crore))

In [661]:
df.price.dtype

dtype('O')

In [662]:
df.head(7)

,land_type,price,price_lakh,location,baths,area,purpose,bed,added_days
0,House,PKR25 Crore,2500.0,"Garden Town, Lahore, Punjab",6,2 Kanal,For Sale,7,2 weeks ago
1,Commercial Plot,PKR60 Crore,6000.0,"Gulberg, Lahore, Punjab",-,2 Kanal,For Sale,-,2 weeks ago
2,House,PKR15 Crore,1500.0,"Gulberg, Lahore, Punjab",6,1 Kanal,For Sale,5,2 weeks ago
3,Commercial Plot,PKR25.5 Crore,2550.0,"Wahdat Road, Lahore, Punjab",-,5.4 Kanal,For Sale,-,3 days ago
4,Residential Plot,PKR7.25 Crore,725.0,"Garden Town, Lahore, Punjab",-,1 Kanal,For Sale,-,2 weeks ago
5,House,PKR6.75 Crore,675.0,"Garden Town, Lahore, Punjab",6,10 Marla,For Sale,7,2 weeks ago
6,Commercial Plot,PKR2 Arab,20000.0,"Gulberg, Lahore, Punjab",-,8 Kanal,For Sale,-,2 weeks ago

In [663]:
temp = df[(df["location"]=="LDA Road, Lahore, Punjab") & (df.land_type=="Residential Plot") & (df.area=="5 Marla")]
round(temp.price_lakh)

2796     20.0
2798     23.0
2804     22.0
2810     24.0
2813     44.0
2814     32.0
2817     15.0
3054     44.0
15712    18.0
17188    28.0
17189    30.0
17190    25.0
17193    36.0
17194    25.0
17201    26.0
17202    22.0
17208    22.0
17211    32.0
18903     NaN
18908    30.0
18910    22.0
18911    38.0
18913    32.0
19825    27.0
19826    28.0
19827    21.0
19828    40.0
19834    29.0
19837    21.0
19838    30.0
19840    14.0
19843    16.0
19845    29.0
Name: price_lakh, dtype: float64

In [664]:
df.at[18903, 'price_lakh'] = round(temp.price_lakh.mean(),2)

# location

In [665]:
def get_loc(loc):
    return loc.split(", Lahore, Punjab")[0].strip()

df.insert(4, "area_location",df.location.apply(get_loc))


# location = []

# for i in df.location:
#     change = i.split(", Lahore, Punjab")[0].strip()
#     location.append(change)

# # df['location'] = location

# df.insert(4, "area_location", location)

In [666]:
df.sample()

,land_type,price,price_lakh,location,area_location,baths,area,purpose,bed,added_days
2410,Residential Plot,PKR6.3 Crore,630.0,"Bedian Road, Lahore, Punjab",Bedian Road,-,9 Kanal,For Sale,-,1 day ago

# Marla

In [667]:
df.area.value_counts()[:5]

area
5 Marla     2626
1 Kanal     2237
10 Marla    2074
3 Marla      711
2 Kanal      442
Name: count, dtype: int64

In [673]:
df[df['area'].str.contains('Sq. Yd', na=False)]

,land_type,price,price_lakh,location,area_location,baths,area,area_value,purpose,bed,added_days
3975,House,PKR3.5 Crore,350.0,"Jamshed Town, Karachi, Sindh","Jamshed Town, Karachi, Sindh",5,120 Sq. Yd.,4.80,For Sale,3,3 weeks ago
6080,Residential Plot,PKR21 Lakh,21.0,"DHA City Karachi, Karachi, Sindh","DHA City Karachi, Karachi, Sindh",-,125 Sq. Yd.,5.00,For Sale,-,1 day ago
9236,House,PKR12.75 Crore,1275.0,"Cantt, Karachi, Sindh","Cantt, Karachi, Sindh",6,500 Sq. Yd.,20.00,For Sale,5,3 weeks ago
9913,Building,PKR40 Crore,4000.0,"I. I. Chundrigar Road, Karachi, Sindh","I. I. Chundrigar Road, Karachi, Sindh",-,600 Sq. Yd.,24.00,For Sale,-,1 month ago
11124,Flat,PKR55 Lakh,55.0,"M. A. Jinnah Road, Karachi, Sindh","M. A. Jinnah Road, Karachi, Sindh",3,122 Sq. Yd.,4.88,For Sale,2,2 years ago
12857,Building,PKR1.7 Crore,170.0,"Gulistan-e-Jauhar, Karachi, Sindh","Gulistan-e-Jauhar, Karachi, Sindh",2,64 Sq. Yd.,2.56,For Sale,-,3 weeks ago

In [672]:
def convert_area(area):

    match = re.search(
        r'(\d+(?:\.\d+)?)\s*(Marla|Kanal|Sq\. Yd\.)',
        str(area),
        re.IGNORECASE
    )

    if not match:
        return None

    value = float(match.group(1))
    unit = match.group(2).lower()

    if unit == 'kanal':
        return value * 20

    elif unit == 'sq. yd.':
        return (value * 9) / 225

    elif unit == 'marla':
        return value

    return None


df.insert(7,"area_value",df.area.apply(convert_area))

In [674]:
df.loc[11124]

land_type                                     Flat
price                                   PKR55 Lakh
price_lakh                                    55.0
location         M. A. Jinnah Road, Karachi, Sindh
area_location    M. A. Jinnah Road, Karachi, Sindh
baths                                            3
area                                   122 Sq. Yd.
area_value                                    4.88
purpose                                   For Sale
bed                                              2
added_days                             2 years ago
Name: 11124, dtype: object