In [88]:
print("okay")

okay

In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (7, 4)

In [90]:
df = pd.read_csv("zameenData.csv")
df.shape
df.head()

,Unnamed: 0,agent,name,land_type,price,location,baths,area,pupose,bed,added_days
0,0,M A Associates,Muhammad Arshad,House,PKR25 Crore,"Garden Town, Lahore, Punjab",6,2 Kanal,For Sale,7,2 weeks ago
1,1,M A Associates,Muhammad Arshad,Commercial Plot,PKR60 Crore,"Gulberg, Lahore, Punjab",-,2 Kanal,For Sale,-,2 weeks ago
2,2,M A Associates,Muhammad Arshad,House,PKR15 Crore,"Gulberg, Lahore, Punjab",6,1 Kanal,For Sale,5,2 weeks ago
3,3,M A Associates,Muhammad Arshad,Commercial Plot,PKR25.5 Crore,"Wahdat Road, Lahore, Punjab",-,5.4 Kanal,For Sale,-,3 days ago
4,4,M A Associates,Muhammad Arshad,Residential Plot,PKR7.25 Crore,"Garden Town, Lahore, Punjab",-,1 Kanal,For Sale,-,2 weeks ago

In [91]:
print(df.columns.tolist())

['Unnamed: 0', 'agent', 'name', 'land_type', 'price', 'location', 'baths', 'area', 'pupose', 'bed', 'added_days']

In [92]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_report = pd.DataFrame({"missing_count": missing, "missing_%": missing_pct})
missing_report[missing_report["missing_count"] > 0]

            missing_count  missing_%
agent                4050      19.69
name                 4064      19.76
land_type              13       0.06
price                  13       0.06
location               13       0.06
baths                  13       0.06
area                   13       0.06
pupose                 13       0.06
bed                    13       0.06
added_days             13       0.06

In [93]:
df = df.drop(columns=["agent", "Unnamed: 0", "name"])
df.columns

Index(['land_type', 'price', 'location', 'baths', 'area', 'pupose', 'bed',
       'added_days'],
      dtype='object')

In [94]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20571 entries, 0 to 20570
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   land_type   20571 non-null  object
 1   price       20571 non-null  object
 2   location    20571 non-null  object
 3   baths       20571 non-null  object
 4   area        20571 non-null  object
 5   pupose      20571 non-null  object
 6   bed         20571 non-null  object
 7   added_days  20571 non-null  object
dtypes: object(8)
memory usage: 1.3+ MB

In [96]:
df.isnull().count()

land_type     20571
price         20571
location      20571
baths         20571
area          20571
pupose        20571
bed           20571
added_days    20571
dtype: int64

In [97]:
df.head()

,land_type,price,location,baths,area,pupose,bed,added_days
0,House,PKR25 Crore,"Garden Town, Lahore, Punjab",6,2 Kanal,For Sale,7,2 weeks ago
1,Commercial Plot,PKR60 Crore,"Gulberg, Lahore, Punjab",-,2 Kanal,For Sale,-,2 weeks ago
2,House,PKR15 Crore,"Gulberg, Lahore, Punjab",6,1 Kanal,For Sale,5,2 weeks ago
3,Commercial Plot,PKR25.5 Crore,"Wahdat Road, Lahore, Punjab",-,5.4 Kanal,For Sale,-,3 days ago
4,Residential Plot,PKR7.25 Crore,"Garden Town, Lahore, Punjab",-,1 Kanal,For Sale,-,2 weeks ago

In [98]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_report = pd.DataFrame({"missing_count": missing, "missing_%": missing_pct})
missing_report[missing_report["missing_count"] > 0]

Empty DataFrame
Columns: [missing_count, missing_%]
Index: []

In [ ]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder.fit_transform(df)

TypeError: 'Index' object is not callable

In [55]:
numerical_features = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = df.select_dtypes(exclude=[np.number]).columns.tolist()

Empty DataFrame
Columns: []
Index: []

In [ ]:
from sklearn.preprocessing import StandardScaler

StandardScaler

In [56]:
numerical_features

[]

In [57]:
categorical_features

['name',
 'land_type',
 'price',
 'location',
 'baths',
 'area',
 'pupose',
 'bed',
 'added_days']

In [31]:
X = df.drop(columns=["price"])
y = df['price']

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'USAMA ALI'

In [ ]:
df['name'].select where